services:
  build:
    image: sinfallas/base-python-uv:3.13
    container_name: build
    hostname: build
    pull_policy: always
    environment:
      TZ: 'America/Caracas'
      UV_PUBLISH_TOKEN: ${UV_PUBLISH_TOKEN}
    volumes:
      - .:/ecoflow_reader
    working_dir: /ecoflow_reader
    command: bash -c "rm -rf dist/ && uv build && uv publish"


