services:
  test:
    image: sinfallas/base-python-uv:3.13
    container_name: test
    hostname: test
    pull_policy: always
    environment:
      TZ: 'America/Caracas'
      UV_PYTHON_DOWNLOADS: true
    volumes:
      - .:/ecoflow_reader
    working_dir: /ecoflow_reader
    command: bash -c "uv pip install --system -e '.[dev]' && pytest -v"

  build:
    image: sinfallas/base-python-uv:3.13
    container_name: build
    hostname: build
    pull_policy: always
    environment:
      TZ: 'America/Caracas'
      UV_PUBLISH_TOKEN: ${UV_PUBLISH_TOKEN}
    volumes:
      - .:/ecoflow_reader
    working_dir: /ecoflow_reader
    command: bash -c "rm -rf dist/ && uv build && uv publish"
