[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "ecoflow-reader"
version = "0.1.0"
description = "Librería en Python para interactuar con la API pública de EcoFlow."
readme = "README.md"
requires-python = ">=3.7"
license = {text = "GPL-2.0"}
authors = [
    {name = "Jesus Palencia", email = "sinfallas@gmail.com"}
]
dependencies = [
    "requests",
    "python-dotenv"
]

[project.urls]
Homepage = "https://github.com/sinfallas/ecoflow_reader"
Repository = "https://github.com/sinfallas/ecoflow_reader.git"

[project.scripts]
ecoflow-cli = "ecoflow_reader.cli:main"
