[tox]
# Matriz de versiones de Python a probar
env_list = py310, py311, py312, py313, py314
isolated_build = True

[testenv]
# Instalamos la librería con sus dependencias de desarrollo
extras = dev
# Comandos a ejecutar en cada versión de Python
commands =
    ruff check src/ecoflow_reader
    ruff format --check src/ecoflow_reader
    mypy src/ecoflow_reader
    pytest -m "not integration"
